### ISSUE TITLE
Format of contentcreated

### ISSUE THREAD

**Issue by jolla56** [iptc/newsinjson#118]
In retrospect I think we might have gone a bit to far declaring this a date-time.

"contentcreated": {             "title": "Content created",             "description": "The date and time when the content of this ninjs object was originally created.",             "type": "string",             "format": "date-time"         }

Hearing the photo metadata discussion during the AGM it was clear that in many cases the exact date and time is not known on old material. So maybe it is better to have it just as a string to make room for what is known?

**Comment by pmougin** [comment]
Sounds good. Besides I suggest we consider aligning ninjs date and time formats with Newsml-G2 ones in order to guarantee complete two-ways interoperability for these values.

**Comment by pauliharman** [comment]
> Indeed that's a bit problematic. Technically that's a breaking change bc prior to the change a processor would expect the value to be a full date-time and implement its system accordingly. As the standard is approved but not published yet (I think), maybe there is room for reasonable adjustments before publication by means of errata or something?

On the one hand - this was only approved yesterday, nobody has implemented anything (and if they had it would have been at their own risk), so pragmatically nothing is actually going to break if we make this change. So maybe we can say it's errata, and/or we are responding to member feedback raised during the autumn meeting.

On the other... I don't think there is any provision in the Rules of Order or elsewhere that would let the Working Group unilaterally make this level of change - I think we could fix errata in the description, but not in the types for the schema itself. So maybe the most we can do is not publish ninjs 2.0 and bring it back to the next Standards Committee meeting... not proceeding with the members' decision (to publish it as-is) is bad, but publishing it with known issues would be worse.

Maybe if we haven't yet made any announcements, we can discuss this in the next session of the ninjs WG and decide how to respond? Sadly I can't make Monday 25th meeting which is itself a problem...

**Comment by pauliharman** [comment]
An alternative might be to leave contentcreated as it is, and propose an contentcreatedapprox sibling element which can be used where a datetime cannot be fully populated.

**Comment by jolla56** [comment]
Meeting November 1st decided to leave it as it is.
