### ISSUE TITLE
Listing social media accounts and contact info in organisations / people

### ISSUE THREAD

**Issue by bquinn** [iptc/newsinjson#131]
@jeremybrooks raised the question that we don't have a way to represent social media accounts related to news item.

(In the specific case from Jeremy, they are for press releases)

These could be either people or organisations.

Each person/organisation may have multiple social media accounts.

How could we represent this?

**Comment by bquinn** [comment]
Brainstorming, use cases may include:
1. Social media account(s) of the issuer of a press release
2. Accounts of other organisations mentioned in the press release (e.g. if a partnership of acquisition is announced)
3. Accounts of a person mentioned in a press release (e.g. CEO of a company)
4. Twitter account that was the source / cause of a news story (e.g. anything Trump ever tweeted led to a news story)
5. Accounts of organisations issuing the news item - BusinessWire, AP? (We don't have a property to exactly match "provider" in G2 - in ninjs examples, people use copyright or infosource. InfoSource definition seems to include the originator. There is a "role" on infosource)

In G2 we have the contactInfo structure which can be re-used in either personDetails or organizationDetails elements. contactInfo has a role that can be used to refine it.

The elements within contactInfo can all be multi-valued. We have `web`, `im`, phone`, `fax`, `email`. They can all have a role attached to them.

We were talking about adding contact info to event information, so perhaps this contactinfo structure can be used for that too.

**Comment by jolla56** [comment]
See #132 for a broader discussion on this.

**Comment by jolla56** [comment]
Also see issue #132 and issue #140
