### ISSUE TITLE
Generic contact info / location info structure that can be used for people, organisations, places and infosources

### ISSUE THREAD

**Issue by bquinn** [iptc/newsinjson#132]
Needed by several different parts of ninjs, including #130 , #120 and more.

We need to have a single way of identifying contact info that can be re-used in all of these places.

It should be as generic as possible to cover existing and future communication methods.

In particular, we will *not* include the NewsML-G2 structures such as email, phone, fax, IM etc.

Use cases:
- physical addresses
- events at a physical location that does not have an address
- events at a location with a name but are well-known so don't need a listed address, such as a football field
- events with no physical location but a virtual location such as a Zoom URL
- geo coordinates (to be able to filter on content, or draw on a map) (do we need both points and polygons? or to be able to say elsewhere when the location is at the exact point or when it's the centre of an administrative region? we have geoJSON already, but the question is how to use it / advise on its use)
- phone, fax, mobile/cell phones, with contact names
- various social media contacts, possibly with a display name that is different from the URI

**Comment by jolla56** [comment]
Also see issue #140

**Comment by bquinn** [comment]
Note that today we discussed this and decided to add contactInfo to infosources and places. We considered adding it to events as well, but decided to wait until we handled editorial planning generally because we may decide to implement it differently.
