### ISSUE TITLE
Compare possible structures of addresses - key/value pairs or specific field names a la G2

### ISSUE THREAD

**Issue by bquinn** [iptc/newsinjson#140]
Today we discussed whether to have
* a generic structure for addresses: an array of type / value objects; or
* specific property names, more like the ones in G2 (defined at https://iptc.org/std/NewsML-G2/2.30/specification/NewsML-G2-2.30-specification.html#_postal_address)

**Comment by jolla56** [comment]
Updated dev schema and my samples document are here: https://github.com/iptc/newsinjson/tree/devgenericcontact/specification

**Comment by jolla56** [comment]
At the meeting Jan 23 2023 we agreed that the suggestion from Jeremy with a more structured address part was the best. See dev schema: https://github.com/iptc/newsinjson/blob/devgenericcontact/specification/ninjs-schema-dev_0.1_v2.0.json
