### ISSUE TITLE
Typo in ninjs 2.0 schema

### ISSUE THREAD

**Issue by jeremybrooks** [iptc/newsinjson#141]
In the description of the organisations array:
`An array of objects describing administrative and functional structures which may, for example, act as as a business, as a political party or not-for-profit party. nar:subject`

Should be
`An array of objects describing administrative and functional structures which may, for example, act as a business, as a political party or not-for-profit party. nar:subject`

**Comment by bquinn** [comment]
you're right - thanks! Although as it's just a spelling error in a
description, I don't think it's worth doing a special update just for that.
We can include the fix in the next release.

**Comment by jolla56** [comment]
Fixed in 2.1 and 1.5
