### ISSUE TITLE
additionalproperties issue

### ISSUE THREAD

**Issue by jolla56** [iptc/newsinjson#143]
We might have an issue with associations and additional properties = false. When I created a sample from a ver 1.3 ninjs it still accepted the description_text thing but should really have complained because in 2.x it should be descriptions: [array].

My quick googling gave the answer that it is hard to combine anyOf with additionalProperties=false.

**Comment by jolla56** [comment]
The issue seemed solved in json schema 2019-09

**Comment by jolla56** [comment]
Alternative proposal in earlier schema versions:
{
  "anyOf": [
    {
      "type": "object",
      "properties": {
        "a": {
          "type": "string"
        }
      }
    },
    {
      "type": "object",
      "properties": {
        "x": {
          "type": "string"
        }
      }
    }
  ],
  "properties": {
    "a": true,
    "x": true
  },
  "additionalProperties": false
}

**Comment by jolla56** [comment]
https://stackoverflow.com/questions/73843324/how-to-merge-two-json-schema-without-additional-properties

**Comment by jolla56** [comment]
Another alternative would be to add name to the core schema, but I don't like that either. We have talked about moving to a newer schema version, so this might be the reason to do so.

**Comment by jolla56** [comment]
And now when I test I can't repeat the problem.

**Comment by jolla56** [comment]
Brendan could replicate the bug in unit tests. And when working more with oXygen I can verify that the problem is there. oXygen seem to demand that you have a validated copy before testing. Because if it is marked as wrong it seems to stay that way even if you switch schema to validate against.

**Comment by bquinn** [comment]
Update: after the meeting, @jeremybrooks solved the JSON Schema problem so we can go with solution 1 above!
