### ISSUE TITLE
Allow renditions to be added to plannedcoverage objects

### ISSUE THREAD

**Issue by bquinn** [iptc/newsinjson#159]
... and we would also need more technical characteristics to be added to renditions to handle everything needed by the DPP project (or a generic key/value pair property but I don't like that idea)

**Comment by trondhuso** [comment]
Now you have two things to be added to videocodec – video codec and Mpeg

https://tldp.org/REF/VLS-User-Guide/x116.html#:~:text=MPEG%20is%20a%20codec.,MPEG%2D4%2C%20...&text=When%20you%20play%20an%20MPEG,for%20subtitles%2C%20and%20so%20on.

According to linked document, mpeg is both a codec and a container format. If I understand the example correct, it is actually a mpeg-4 codec

When I searched for XDCam I found a Sony camera…
Searched a bit more and found this:
https://creativecow.net/forums/thread/sony-mxf-or-xdcam-ex-whats-the-best-intermediate/
Where it says this:
Sony MXF (.mxf) and XDCAM EX (.mp4)

So, yes – I think you that information can be stored in the video codec

T


From: Brendan Quinn ***@***.***>
Date: Tuesday, 28 November 2023 at 10:50
To: iptc/newsinjson ***@***.***>
Cc: Subscribed ***@***.***>
Subject: Re: [iptc/newsinjson] Allow renditions to be added to plannedcoverage objects (Issue #159)

Technical characteristics that we need to add to support the examples in @amitesharqiva<https://github.com/amitesharqiva> 's doc:
Attribute
Example
Found in examples from
Suggested NewsML-G2 equivalent
Audio Channels
4
Arqiva, CNN
audiochannels (attribute in newsContentCharacteristics)
Channel frequency
11.501,500 V
Arqiva
Doesn't exist in NewsML-G2
Audio frequency
48000
CNN
audiosamplerate (attribute in newsContentCharacteristics)
Audio quantization
16
CNN
Doesn't exist in NewsML-G2
Format FPS
29.97
CNN
videoframerate (attribute in newsContentCharacteristics)
Mpeg
MPEG 4 420
Arqiva
I think this can go under video codec?
Bitrate
15 Mbps
Arqiva
videoavgbitrate (attribute in newsContentCharacteristics)
Aspect Ratio
16:9
Arqiva
videoaspectratio (attribute in newsContentCharacteristics)
Video format
1920 x 1080
Arqiva, CNN
height, width (attributes in newsContentCharacteristics)
Video codec
XDCAM ***@***.*** MXF
Arqiva, CNN
videocodec (attribute in newsContentCharacteristics)
