### ISSUE TITLE
Handle SRT Flow event attributes in live events in ninjs

### ISSUE THREAD

**Issue by bquinn** [iptc/newsinjson#164]
Word doc shared by @amitesharqiva :

[DPP LPX Flow Parameters v1.docx](https://github.com/iptc/newsinjson/files/14221130/DPP.LPX.Flow.Parameters.v1.docx)

Quick summary of parameters needed (highlighted fields from word doc):
* Source name (short text string)
* Source type: SRT Listener, SRT Caller. (these will be ood enough for the hackathon. might need to add RTP, RIST, MediaConnect, Zixi Push,  in the future)
* Fields from SRT Listener example:
  * Max bitrate bits/sec (number)
  * CIDR ?? (check if we need it, it wasn't highlighted in the doc)
  * Port (number 1024-65535)
  * SRT Password (optional, short text string)
* Fields from SRT Caller example:
  * Max bitrate bits/sec (number)
  * Min latency (ms) (number, should be between 100 and 15,000 ms)
  * port (number 1024-65535)
  * listener address (valid IP address or fully qualified domain name)
  * stream ID (optional, string up to 255 chars - first and last characters must be [a-zA-Z0-9] all other characters must be [a-zA-Z0-9-_])
  * SRT Password (optional, short text string)
* Fields from Profile form:
  * Codec (AVC and others...?)
  * Framerate numerator / framerate denominator
  * width, height
  * Scan type (progressive or interlaced)
  * Bitrate (bps)
  * GOP (frames) (number or "unspecified")
  * Colourspace (dropdown/enum, values are: REC_601, REC_709, HLG_2020, HDR10)
  * Rate control mode (dropdown/enum, values are: QVBR, VBR, CBR)

**Comment by himslm01** [comment]
The feedback I got was that some of the properties naturally fit in the url, such as the stream id, but some don’t naturally fit.

For example from the feedback, max bitrate and min latency are more meta. They calibrate the SRT process.

It was suggested that a good process flow should enable a process to lift a URL as is without any processing and drop in to a SRT application.

The thoughts we that max bitrate and latency need to be provided outside of the URL. And an SRT application could assume some default values for these and/or validate values.

From the feedback, we can imagine a world where max bitrate forms part of a negotiation between a sender and receiver to manage network capacity. Or is calculated with properties of the renditions intended to be passed around.
