### ISSUE TITLE
event status (for DPP LPX)

### ISSUE THREAD

**Issue by bquinn** [iptc/newsinjson#165]
Conor from Reuters has requested that we have an eventStatus property which is different from the pubstatus.

The difference is that pubstatus is about the coverage, eventstatus is about the event itself.

          type: string
          enum:
            - cancelled
            - scheduled
            - live
            - completed

Compare this with our G2 https://cv.iptc.org/newscodes/speventstatus/ vocabulary which has:

-	Pre-event
-	Mid-event
-	Post-event
-	Postponed
-	Suspended
-	Halted
-	Forfeited
-	Rescheduled
-	Delayed
-	Canceled (note US spelling!)
-	Intermission
-	If-necessary
-	Discarded

**Comment by himslm01** [comment]
In our LPX discussions months before the hack, it was mooted that it would be nice if there were events which could be used pre-event to spin up infrastructure. It also very much depends on your definition of an event.

Take for a typical news press conference example where one broadcaster is on site sending back a pool feed.

I very much doubt that the stream will start at the point when the press conference is about to start. The stream might start hours before. There'd be idents, and A-V sync checks, etc. Then maybe the line is used for the host broadcaster to do a spot into their rolling news channel. At some point the press conference will start. blah blah. At the end of the press conference the line might again be used for a rant into the live channel.

Was the event the press conference?
At what point did the event switch from being pre-event to mid-event to post-event?
Is the event different for the host broadcaster than for the broadcasters the stream is being pooled with?
Do we want signalling to say when "the line is up" but the event has not started? That would be very useful for spinning up your resources in the cloud.

I'm not wanting to boil the ocean, but if LPX is to be useful for system-to-system signalling it's got to signal useful things. I'd like to be able to draw/see flow-charts indicating which signals, be they datetimes or properties, should be used to drive the different stages of "a recording".
