### ISSUE TITLE
Should we use the newscoveragestatus CV?

### ISSUE THREAD

**Issue by bquinn** [iptc/newsinjson#176]
We just noticed that this exists... defined for NewsML-G2 / EventsML-G2. Is it useful for ninjs planning items?

https://cv.iptc.org/newscodes/newscoveragestatus/

Here are the current values:
| ID | Term name | Description
| --- | --- | ---
| int | coverage intended | None
| notdec | coverage not decided yet | None
| notint | coverage not intended | None
| onreq | coverage upon request | None

Related: #165

**Comment by himslm01** [comment]
I've just had a look through BBC News' ingest/mam system to look for the statuses it includes for future/current/past recordings (which roughly equate to events) in case this set is useful when finding or constructing a controlled vocabulary.

- On-Time
- Lining-Up
- Lined-Up
- Ready To Record
- Recording
- Feeding
- Complete
- Incomplete
- Delayed
- Cancelled
- Tape Cueing
- Record Failed 

I'm not saying this is necessarily the best list, or even a complete list, but it's one I could get quickly.

**Comment by bquinn** [comment]
NewsML-G2 has occurStatus (with CV https://cv.iptc.org/newscodes/eventoccurstatus/) and newsCoverageStatus (with CV https://cv.iptc.org/newscodes/newscoveragestatus/) and we think that would cover most of not all of the cases covered by speventstatus in current examples.

Both of these elements are part of eventDetails. ie they describe the event itself, not the individual planning item.
