### ISSUE TITLE
JSON Schema issues

### ISSUE THREAD

**Issue by redaktor** [iptc/newsinjson#2]
Could you please make the JSON Schema draft4 compatible?
SeeAlso: https://github.com/SchemaStore/schemastore/pull/9

I would also prefer to have a `title` in each property.
E.g. keys like "copyrightholder" should have a `title` "copyright holder" since they are not camelcased and a machine would not be able to find word boundaries.

And there were approved changes, see http://dev.iptc.org/ninjs-Approved-Changes
I can't find them in the Schema.

Additionally I would like to know why `additionalProperties` are `false`in classes like "Person" etc.

**Comment by jolla56** [comment]
Suggestions added so we close the issue.
