### ISSUE TITLE
Move 2.2 examples to 3.0 if necessary and remove the examples.2.2 folder from PR branch

### ISSUE THREAD

**Issue by bquinn** [iptc/newsinjson#200]
Examples are currently in https://github.com/iptc/newsinjson/tree/events-planning/examples/2.2

**Comment by jolla56** [comment]
Some of the samples in the 3.0 folder need to be fixed to. Doing that now.

**Comment by jolla56** [comment]
https://github.com/iptc/newsinjson/pull/208
