### ISSUE TITLE
Add alt ids   CR 10-04

### ISSUE THREAD

**Issue by jolla56** [iptc/newsinjson#3]
Change Request number: ninjs CR 10-04
Standard to be changed: ninjs
Standard’s version to be changed:1.1

**Description of the change: (free-text)**
Add a pattern property for altids to ninjs of the form

`altid_[a-z0-9_]+`

In other words, allow for alternative ids prefixed by "`altid_`" with a string of numbers, letters and underscores to identify which altid is being used. The type of the property is "string".

**Rationale for the change:**
Providers often need to supply alternative identifiers for news items, in addition to the master id. Often there needs to be more than one.

**Formalised change request:**

Name: `altid_[a-z0-9_]+`
Definition: An alternative identifier for the item.
Data type: string

**Comment by jolla56** [comment]
JYOUNGAP: 
This capability is definitely essential. I'd like to propose an alternative implementation where a single object named "alt_ids" is used as a container for any and all application specific identifiers that an implementer requires.  Contained properties could be of any valid type.  This would allow applications to use names (and types) of their exact choosing rather than always a modified version.  

 alt_ids {

  id1: "0x01",

  id2: 2,

  id3: null

}

**Comment by jolla56** [comment]
JAYSON:
I feel these altIds may be useful (I can already see a use case at BW, if we start to use this standard). I like the idea of grouping these as suggested by jyoungap. This adds some complexity but not as much as some of the existing structures like: Renditions. I am in favor of having this addition and will likely use it.
Ya know .. after actually trying to use this sort of thing, I prefer doing this using a pattern as the OP suggests

**Comment by jolla56** [comment]
Using the pattern property could look like this:
        "^altid_[a-zA-Z0-9_]+": {
            "title": "Alternative id's",
            "description": "An alternative id. The name need to start with altid_ ",
            "type": "string"
        }

**Comment by jolla56** [comment]
Looking in the spreadsheet with samples both AP and Reuters seem to use an object which could be like this in the schema, allowing providers both name and type of their id's:
        "altids": {
            "description": "Alternative id's of the item",
            "type": "object",
            "additionalProperties": true
        }

**Comment by jolla56** [comment]
Putting both variants in a sample would look like this. Both validates:
{
	"uri": "test:123",
	"title": "Test of alt id's",
	"altid_tt_id": "tt_123456",
	"altid_np": "123456",
	"altids": {
	  "tt_id":   "tt_123456",
	  "npid": 123456
	}
}

**Comment by bquinn** [comment]
Agreed today to add the altids structure to the dev schema.

**Comment by jolla56** [comment]
Added to dev-schema:
        "altids": {
            "title": "Alternative id",
            "description": "Alternative id's of the item. It is up to the individual provider to name and set type on the alternative id's they like to use.",
            "type": "object",
            "additionalProperties": true
        }
