### ISSUE TITLE
News-sector information  CR 10-32

### ISSUE THREAD

**Issue by jolla56** [iptc/newsinjson#32]
New property “sector”:
```
"sector": {
            "description" : "$$TT: Designator for the 'big 5' ways of grouping content (inrikes, utrikes, etc).",
            "type": "string",
            "enum" : ["INR", "UTR", "EKO", "KLT", "SPT"]
        }
```

This is swedish abbreviations for DOMestic, FOReign, FINance, CULture and SPOrts.

Rationale for the change: (free-text)
We tried to move away from this and use products instead. But our custumers wanted the old terms still. So instead of them mapping randomly we added this information.

It could maybe be an altid?

**Comment by bquinn** [comment]
I think altId doesn't really work, as these terms don't _identify_ the content, they merely _categorise_ it.

But we have now introduced `genre` which should work well!

```
"genre": [
  {
    "name": "Domestic news",
    "scheme": "http://tt.se/schemes/example-tt-news-sector",
    "code": "INR"
  },
  { ... other genres if necessary... }
]
```

Would that work @jolla56 ?

**Comment by jolla56** [comment]
Yes, genre would work and that have already been added to 1.3.

**Comment by pmougin** [comment]
Hi, genre doesn't sound quite right. DOMestic, FOReign, FINance, CULture and SPOrts likely identify subject matter of the news content. Hence using the "subject" property would be appropriate.
