### ISSUE TITLE
"profile" in ninjs doesn't match "profile" in the News Architecture

### ISSUE THREAD

**Issue by bquinn** [iptc/newsinjson#33]
Philippe M:
> At AFP they use profile in NewsML-G2 to store the kind of client application the content is created for. It would usually be very environment specific.

**Comment by jolla56** [comment]
Definition in NINJS 1.1: 
        "profile": {
            "title": "Profile",
            "description": "An identifier for the kind of content of this news object. This can be any string but we suggest something identifying the content such as 'text-only' or 'text-photo'. (Investigate if this align with NewsML nar:profile or not.)",
            "type": "string"
        },


Definition in NewsML-G2:
	<xs:element name="profile" type="VersionedStringType">
		<xs:annotation>
			<xs:documentation>The name of the structural template (aka profile) used for the generation of the Item.</xs:documentation>
		</xs:annotation>
	</xs:element>

**Comment by jolla56** [comment]
https://www.iptc.org/std/NewsML-G2/guidelines/#profile

 https://iptc.org/std/NewsML-G2/2.28/specification/NewsML-G2-2.28-specification.html#profile-profile

Maybe same thing after all. Check all documentation.

**Comment by jolla56** [comment]
NewsML-G2 guidelines and schema will be updated. Look at the changes and update ninjs description.

**Comment by jolla56** [comment]
Documentation in schema updated.
