### ISSUE TITLE
version should be positive integer?

### ISSUE THREAD

**Issue by bquinn** [iptc/newsinjson#41]
The NewsML-G2 schema says:

```
<xs:attribute name="version" type="xs:positiveInteger" use="optional" default="1">
<xs:annotation>
<xs:documentation>The version of the Item. </xs:documentation>
</xs:annotation>
</xs:attribute>
```

but "version" in ninjs is a string:

```
 "version": {
    "title": "Version",
    "description": "The version of the news object which is identified by the uri property. nar:newsItem@version",
    "type": "string"
},
```

should we change it? Technically that would be a breaking change.

**Comment by nitmws** [comment]
Well, ninjs was designed as “more flexible”, not everything was strictly copied from NewsML-G2.

Therefore the version was defined as string, numeric values converted to a string may be used.

 

Best,

Michael

**Comment by jolla56** [comment]
We came to the conclusion not to make version strict postive integers so closing the issue for now.
