### ISSUE TITLE
Link to schema name and version

### ISSUE THREAD

**Issue by jolla56** [iptc/newsinjson#43]
Property in NINJS to indicate which schema and version it should be checked agains (if any). We have asked the json schema group for advise.

**Comment by nitmws** [comment]
Note: in NewsML-G2 the root element has an attribute (@standardversion) for the version of the applied NewsML-G2 specification = the corresponding XML Schema. And each XML Schema is exactly for one version of NewsML-G2.

**Comment by bquinn** [comment]
Here is the conversation from the JSON Schema Slack community, including two of the current JSON Schema maintainers:

> brendanquinn  4:32 PM Hi all, we’ve had a request to have a mechanism to refer to “the schema against which this document should be validated” - is there any kind of precedent or best practice for that?
> Bruce  6:02 PM All I’ve seen is this: https://snowplowanalytics.com/blog/2014/05/15/introducing-self-describing-jsons/
Snowplow
Introducing self-describing JSONs
Snowplow – Snowplow. Take control of your data and use it to differentiate.

> relequestual  6:22 PM @brendanquinn No, there is not. There was an issue opened recently about this again. Let me find it
> 6:22 https://github.com/json-schema-org/json-schema-spec/issues/828
> 6:24 It's something I expect we will address, but not any time soon
> 6:25 In the meantime, either you can just set $schema to your schema URI in your JSON data.
> 6:25 Or whatever you want

> brendanquinn  6:26 PM you can?! I guess there’s no definition of what that means so there’s nothing stopping us…?
> brendanquinn  6:27 PM I assumed there was an (unwritten?) rule saying that anything with “$schema” in it was a schema definition…
>>relequestual  3 hours ago I THINK VSCode behaves this way... but other IDEs do not

> brendanquinn  6:28 PM I know it’s not a spec, but… https://json-schema.org/understanding-json-schema/reference/schema.html
>> The $schema keyword
>> The $schema keyword is used to declare that a JSON fragment is actually a piece of JSON Schema. It also declares which version of the JSON Schema standard that the schema was written against.
> 6:29 https://json-schema.org/draft/2019-09/json-schema-core.html#rfc.section.8.1.1 says
>> The “$schema” keyword SHOULD be used in a resource root schema. It MUST NOT appear in resource subschemas.

> and

>> The “$schema” keyword is both used as a JSON Schema feature set identifier and as the identifier of a resource which is itself a JSON Schema

> (emphasis added)
> relequestual  6:38 PM Right, for a JSON which is a JSON Schema it's defined
> although the URI doesn't mean there's a downloadable meta-schema there
> handrews  7:16 PM I wouldn’t use $schema in an instance because it makes it look like a JSON Schema
> I’d use some other keyword to avoid confusion
> Just pick your own convention and stick with it
> JSON Schema, as a design principle, does not pre-constrain what instances it can describe and therefore cannot specify an instance keyword. (edited) 

So the recommendation seems to be to just create our own property... which would then need to be added to our schemas, and therefore could only be used in future versions (unless we want to go back and edit old schemas, and I'm pretty sure we don't want to do that).

But it's better than nothing.

**Comment by jolla56** [comment]
Thanks Michael,

That is interesting input and something similar to what we were talking
about.



Johan

Johan Lindgren, TT, 070-6528007


Den mån 13 jan. 2020 kl 21:07 skrev Brendan Quinn <notifications@github.com

**Comment by jolla56** [comment]
From NewsML-G2:

		<xs:attribute name="standard" type="xs:string" use="required">
			<xs:annotation>
				<xs:documentation>The IPTC standard with which the Item is conformant.</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="standardversion" use="required">
			<xs:annotation>
				<xs:documentation>The major-minor version of the IPTC standard with which the Item is conformant.</xs:documentation>
			</xs:annotation>
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:pattern value="[0-9]+\.[0-9]+" />
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="conformance" type="xs:string" use="optional" default="core">
			<xs:annotation>
				<xs:documentation>The conformance level with which the Item is conformant.</xs:documentation>
			</xs:annotation>
		</xs:attribute>

**Comment by bquinn** [comment]
Discussion on 27/1:
Create new properties, `standard`, `standardversion` and `schemauri`. In a new property. 

```
$standard": {
  "name": "",
  "version": "",
  "schema": "" /* or "schemauri"? */
}

```"

Alternative is to create three new top-level properties and not to group them together.

**Comment by jolla56** [comment]
Added to dev schema:

        "$standard": {
            "title": "Standard",
            "type": "object",
            "description": "An object with information about standard, version and schema this instance is valid against. nar:standard, nar:standardversion and xml:schema",
            "additionalProperties": false,
            "properties": {
                "name": {
                    "type": "string",
                    "title": "Name of standard. ",
                    "description": "For example ninjs. nar:standard"
                },
                "version": {
                    "type": "string",
                    "title": "Version of standard. ",
                    "description": "For example 1.2. nar:standardversion"
                },
                "schema": {
                    "type": "string",
                    "format": "uri",
                    "title": "Schema",
                    "description": "The uri of the json schema to use for validation."
                }
            }
            
        }
