### ISSUE TITLE
Representing Trust Indicators in ninjs

### ISSUE THREAD

**Issue by bquinn** [iptc/newsinjson#44]
We have created an experimental NewsCodes controlled vocabulary to represent Trust Indicators:
http://cv.iptc.org/newscodes/trustindicator/

In NewsML-G2 these can be repreesented with "qualified links", such as

`<link reluri="http://cv.iptc.org/newscodes/trustindicator/editorial-policy" href="https://www.bbc.com/editorialguidelines/guidelines/editorial-standards">`

or using QCodes:

`<link rel="trustindicator:editorial-policy" href="https://www.bbc.com/editorialguidelines/guidelines/editorial-standards">`

We would like to have a way to express these in ninjs as well.

**Comment by jolla56** [comment]
The alternatives we discussed at the meeting on Jan 13th was to either use associations or create a new structure.

**Comment by bquinn** [comment]
Option 1: Use associations

```
{
  "uri": "http://www.businesswire.com/news/home/20130515006361/en",
  "type":"composite",
  "mimetype": "application/x-resource+json;level=composite",
  "version": "1",
  "versioncreated": "2013-05-16T04:01:00Z",
  "headline": "Dell Redefines Workstation Computing Boundaries with Smallest Tower and Most Powerful Rack Workstations",
  "body_xhtml": " [ ... ]",
  "associations": {
    "trustindicator:editorial-policy": {
      "uri":"https://www.bbc.com/editorialguidelines/guidelines/editorial-standards",
      "type":"component", /* ??? */
    }
}

```
Pros: doesn't need changes to the standard
Cons: It isn't really what associations were intended to handle. Also the `type` of the link isn't really correct - perhaps we need another possible `type` value?

**Comment by bquinn** [comment]
Option 2: Create a new structure

Something like...

```
{
  "uri": "http://www.businesswire.com/news/home/20130515006361/en",
  "type":"composite",
  "mimetype": "application/x-resource+json;level=composite",
  "version": "1",
  "versioncreated": "2013-05-16T04:01:00Z",
  "headline": "Dell Redefines Workstation Computing Boundaries with Smallest Tower and Most Powerful Rack Workstations",
  "trustindicators": [
    { "indicator": "http://cv.iptc.org/newscodes/trustindicator/editorial-policy",
      "value": "https://www.bbc.com/editorialguidelines/guidelines/editorial-standards"
    },
    { "indicator": "http://cv.iptc.org/newscodes/trustindicator/no-bylines-policy",
      "value": "https://www.bbc.com/news/help-41670342#authorexpertise"
  ],
  "body_xhtml": " [ ... ]"
}
```

Pros:
* It's clear what's going on
* A full URI can be included - don't think a property name can be a URI?
Cons:
* Requires a change to the spec

**Comment by jolla56** [comment]
Can you explain what the indicator and value represent? Can we compare this with the subject etc structure with name, code, scheme, rel - properties?

**Comment by bquinn** [comment]
Option 3: A generic link/rel structure.

```
{
  "uri": "http://www.businesswire.com/news/home/20130515006361/en",
  "type":"composite",
  "mimetype": "application/x-resource+json;level=composite",
  "version": "1",
  "versioncreated": "2013-05-16T04:01:00Z",
  "headline": "Dell Redefines Workstation Computing Boundaries with Smallest Tower and Most Powerful Rack Workstations",
  "links": [
    { "reluri": "http://cv.iptc.org/newscodes/trustindicator/editorial-policy",
      "href": "https://www.bbc.com/editorialguidelines/guidelines/editorial-standards"
    },
    { "reluri": "http://cv.iptc.org/newscodes/trustindicator/no-bylines-policy",
      "href": "https://www.bbc.com/news/help-41670342#authorexpertise"
  ],
  "body_xhtml": " [ ... ]"
}
```

**Comment by bquinn** [comment]
After discussion, keeping consistency with other metadata structures, 

```
"trustindicator": [
	 {
            "name" : "The BBC's Editorial Standards",
            "scheme" : "http://cv.iptc.org/newscodes/trustindicator/",
            "code" : "editorial-policy",
            "href": "https://www.bbc.com/editorialguidelines/guidelines/editorial-standards"
        }
]
```

`href` keeps consistency with `rendition` as a dereferenceable link.
We think we don't need `rel`. Can re-consider adding it in the future.
Keeping the word `trustindicator` singular for consistency with `subject`, `person` etc even though they are all arrays.

**Comment by jolla56** [comment]
Added to dev schema:
        "trustindicator": {
            "title": "Trust indicator",
            "description": "An array of objects to allow links to documents about trust indicators. (nar:link)",
            "type": "array",
            "items": {
                "type": "object",
                "additionalProperties": false,
                "properties": {
                    "title": {
                        "title": "Title",
                        "description": "The title of the resource being referenced.",
                        "type": "string"
                    },
                    "scheme": {
                        "title": "Scheme",
                        "description": "The identifier of a scheme (= controlled vocabulary) which includes a code for the trust indicator",
                        "type": "string",
                        "format": "uri"
                    },
                    "code": {
                        "title": "Code",
                        "description": "The code for the trust indicator in a scheme (= controlled vocabulary) which is identified by the scheme property",
                        "type": "string"
                    },
                    "href": {
                        "title": "href", 
                        "description": "The URL for accessing the trust indicator resource.",
                        "type": "string",
                        "format": "uri"
                    }
                }
            }
        }
