### ISSUE TITLE
Look at sourcefabric / superdesk extensions to ninjs

### ISSUE THREAD

**Issue by bquinn** [iptc/newsinjson#45]
See https://github.com/superdesk/superdesk-core/blob/d7971cfd60524eb6701639424133e3b9cd1d7b4e/superdesk/publish/formatters/ninjs_formatter.py#L79:

> The schema we use for the ninjs format is an extension
>     of `the standard ninjs schema <http://www.iptc.org/std/ninjs/ninjs-schema_1.1.json>`_.
>     *Changes from ninjs schema*:
>     * ``uri`` was replaced by ``guid``: ``uri`` should be the resource identifier on the web
>         but since the item was not published yet it can't be determined at this point
>     * added ``priority`` field
>     * added ``service`` field
>     * added ``slugline`` field
>     * added ``keywords`` field
>     * added ``evolvedfrom`` field
>     * added ``source`` field
>     Associations dictionary may contain entire items like
>     in `ninjs example <http://dev.iptc.org/ninjs-Examples-3>`_ or just the item ``guid``
>     and ``type``. In the latest case the items are sent separately before the package item.

**Comment by jolla56** [comment]
Its in the comparison sheet I put together last autumn.


Johan

Johan Lindgren, TT, 070-6528007


Den fre 21 feb. 2020 kl 14:09 skrev Brendan Quinn <notifications@github.com

**Comment by jolla56** [comment]
Interesting that the items referred to in the spreadsheet look a little
different compared to the schema you can find above.

This is the link we have in the sheet:
https://superdesk.readthedocs.io/en/latest/schema.html


Johan

Johan Lindgren, TT, 070-6528007


Den fre 21 feb. 2020 kl 21:35 skrev Johan Lindgren <johan.lindgren@tt.se>:

**Comment by jolla56** [comment]
I've added the whole schema to our comparison sheet.
