### ISSUE TITLE
Add genre to ninjs

### ISSUE THREAD

**Issue by jolla56** [iptc/newsinjson#46]

**Comment by jolla56** [comment]
The whole list is here: http://cv.iptc.org/newscodes/genre/

**Comment by jolla56** [comment]
"genre": {
            "title": "Genre",
            "description": "A nature, intellectual or journalistic form of the content. nar:genre",
            "type": "array",
            "items": {
                "type": "object",
                "additionalProperties": false,
                "properties": {
                    "name": {
                        "title": "Name",
                        "description": "The name of the genre",
                        "type": "string"
                    },
                    "rel": {
                        "title": "Relationship",
                        "description": "The relationship of the content of the news object to the genre. Needed?",
                        "type": "string"
                    },
                    "scheme": {
                        "title": "Scheme",
                        "description": "The identifier of a scheme (= controlled vocabulary) which includes a code for the genre. Normally  http://cv.iptc.org/newscodes/genre/",
                        "type": "string",
                        "format": "uri"
                    },
                    "code": {
                        "title": "Code",
                        "description": "The code for the genre in a scheme (= controlled vocabulary) which is identified by the scheme property",
                        "type": "string"
                    }
                }
            }

**Comment by jolla56** [comment]
The above follow the structure for subjects etc.

One question is if an object can belong to more than one genre, or if genre is singular. If so we can remove the array.

**Comment by jolla56** [comment]
To align with the NAR we should keep the array.

During the phone meeting on March 9th we decided that rel is not needed.

**Comment by bquinn** [comment]
Just to have an example noted down, it would look like:

```
{
  ...
   "genre": [
      {
         "name": "Opinion",
         "scheme": "http://cv.iptc.org/newscodes/genre/"
         "code": "Opinion"
      }
   ],
   ...
}
```
