### ISSUE TITLE
Retire "scheme" and "code" and use only "uri" for CV references

### ISSUE THREAD

**Issue by bquinn** [iptc/newsinjson#54]
Came up in discussion at the ninjs call on 18 May 2020.

Something to consider for 2.0?

**Comment by bquinn** [comment]
Considerations:

- URIs and strings are not the same: comparison algorithms are different for example.
- Some people may be using code on its own, which is legal in 1.x:
`"person": { "name": "Fred Smith", "code": "123" }`
is perfectly valid. But to turn this into a URI would require users to point to some controlled vocabulary somewhere which makes things more difficult.

**Comment by jolla56** [comment]
Agree, we do not gain anything by enforcing either or of literal and uri. If a provider has a use-case of both having the uri and the literal they should be allowed to do so.

**Comment by jolla56** [comment]
Done in the latest version of the dev-2.0 schema
