### ISSUE TITLE
Support podcast properties a la Media RSS

### ISSUE THREAD

**Issue by bquinn** [iptc/newsinjson#62]
Apple podcasts still point to Media RSS specs from 2003 and use very old constructs:

https://help.apple.com/itc/podcasts_connect/#/itcb54353390

Is there a way we can make ninjs support podcast behaviour, perhaps even talk to podcast providers to see what they would like to add, so people could mark up podcasts using ninjs instead of Media RSS?

**Comment by jolla56** [comment]
Maybe step 1 is to map ninjs to media RSS and see what maps directly and what needs adding.

**Comment by jolla56** [comment]
I had a look at this and to my understanding RSS is a XML standard with this podcast extensions defined by Apple. So is this a question for NAR/NewsML-G2 primarily?

**Comment by jolla56** [comment]
Closed since we have the same type of discussion in #69.
