### ISSUE TITLE
Suggestion for discussion: change all patternProperties objects to well-defined property names in 2.0

### ISSUE THREAD

**Issue by bquinn** [iptc/newsinjson#63]
This has come from our discussion of Avro and ProtoBufs in #56.

Protocol Buffers and Avro expect every field name (=property) to be well defined, and they are "compiled" into integer IDs in the protobuf schema.

In ninjs, we have many properties whose names change between provider implementations (eg headline_XXX) or even between instance documents (eg renditions: "main": {}, "small": {}). These cannot be compiled into protobuf schemas in a generic way, they would have to be done separately for each provider.

So should we re-work the entire schema so we don't have any patternProperties?

So renditions, for example, would change from
```
"renditions": {
    "main" : {
            "href" : "http://hosted.ap.org/photos/2/2643c588-dc8d-4923-bebd-e3b904edbb3a-big.jpg",
            "mimetype": "image/jpg",
            "title" : "Mid Resolution",
            "height" : 281,
            "width" : 429
    },
        "small" : {
            "href" : "http://hosted.ap.org/photos/2/2643c588-dc8d-4923-bebd-e3b904edbb3a-small.jpg",
            "mimetype": "image/jpg",
            "title" : "Low Resolution",
            "height" : 117,
            "width" : 179
        }
}
```
to
```
"renditions": [
    {
        "name": "main",
        "href" : "http://hosted.ap.org/photos/2/2643c588-dc8d-4923-bebd-e3b904edbb3a-big.jpg",
        "mimetype": "image/jpg",
        "title" : "Mid Resolution",
        "height" : 281,
        "width" : 429
    },
    {
        "name": "small",
        "href" : "http://hosted.ap.org/photos/2/2643c588-dc8d-4923-bebd-e3b904edbb3a-small.jpg",
        "mimetype": "image/jpg",
        "title" : "Low Resolution",
        "height" : 117,
        "width" : 179
    }
]
```

It's definitely a breaking change, and it doesn't use the cool patternProperties feature of JSON SChema, but it might make some things a lot easier...

**Comment by jolla56** [comment]
Interesting thought. But it also breaks possibilities for providers to insert their own properties. To do that they would need to create their own json schema and add their properties. And then compile for each provider.

**Comment by bquinn** [comment]
Today's discussion: how to handle patternProperties in this way?

We could convert

`"body_AAA": {},
 "body_BBB": {} `

to

```
"body": [
  { "type": "AAA", ... },
  { "type": "BBB", ... }
]
```

**Comment by jolla56** [comment]
This is done in the dev-2.0 schema proposal.
