### ISSUE TITLE
Improve definition / documentation of rendition "format"

### ISSUE THREAD

**Issue by bquinn** [iptc/newsinjson#64]
How is it different from "mimetype" ?

The description just says "Binary format name".

**Comment by jolla56** [comment]
It is used in renditions and the documentation points to NAR:
"A refinement of a generic content type (i.e. IANA MIME type) by a value from a controlled vocabulary - expressed by a QCode"
Not sure if that answers the question.

**Comment by jolla56** [comment]
From NewsMLG2-schema:
"A refinement of a generic content type (i.e. IANA MIME type) by a value from a controlled vocabulary - expressed by a QCode"

**Comment by jolla56** [comment]
We found this, but it only applies to NewsML-1
https://cv.iptc.org/newscodes/format/

**Comment by jolla56** [comment]
Contentypevariant in NewsMLG2: A refinement of a generic content type (i.e. IANA MIME type) by a literal string value.

**Comment by jolla56** [comment]
Changed in the dev 2.0 schema.
