### ISSUE TITLE
Provide better guidance for various attributes (such as `rel`)

### ISSUE THREAD

**Issue by sdavids13** [iptc/newsinjson#70]
I am trying to infer guidance as to how various objects should be used to indicate "what" type of subject/person/place/etc a particular piece is referring to and I'm seeing some conflicting usage of the `rel` and `scheme`/`code` attributes. First, it seems like `subject`, `person`, `place`, `organisation`, etc. fields use the `scheme` and `code` values to describe the `name` (value) attribute as seen here:
```
        {
            "name" : "Italy",
            "rel" : "mentions",
            "scheme" : "http://cvx.iptc.org/iso3166-1a2/",
            "code" : "it"
        }
```

I am also trying to track down if there is some sort of controlled (or suggested) values for the `rel` attribute, based on the current examples I see the following `rel` values provided for these objects:

- `subject`: `about`
- `person`: `about`
- `place`: `mentions`
- `organisation`: `mentions`

Now, when I look at other objects such as `infosource` it's `schema`/`code` values are used to provides a better description of the `rel` attribute, not a specific code for the `name` attribute as seen here:
```
        {
            "name": "Susan Smith",
            "rel": "Interview source",
            "scheme": "http://cv.iptc.org/newscodes/contentprodpartyrole/",
            "code": "interviewee"
        }
```

The "why" I'm trying to get clarity on the documentation and the usages on these fields is because I'm trying to determine the "appropriate" location/usage for relatively simple things such as hashtags. For example, NewsML provides really simple documentation to know how to consistently deal with hashtags as seen [here](https://www.iptc.org/std/NewsML-G2/guidelines/#hashtags):
```
<contentMeta>
    ...
    <keyword role="drol:hashtag">#iptcrocks</keyword>
    ...
</contentMeta>
```

When trying to map this (and assuming that keywords is still not implemented via https://github.com/iptc/newsinjson/issues/20) should I provide guidance to use `subject` instead and use the NewsML `role` in place of the `rel`? Such as:
```
        "subject": [{
            "name" : "#iptcrocks",
            "rel" : "drol:hashtag"
        }]
```

Alternatively, with looking at how `infosource` has used the `schema`/`code` to describe the `rel` slightly more specifically another option might be:
```
        "subject": [{
            "name" : "#iptcrocks",
            "rel" : "about",
            "scheme": "http://cv.iptc.org/newcodes/descriptionrole/",
            "code": "drol:hashtag"
        }]
```

To me, I think the former would be more desirable, but am unsure based on the documentation and examples I have seen. I believe end-users could be better served if further guidance/clarification/samples can be provided.

**Comment by pmougin** [comment]
Hello Steve,

This particular infosource example is incorrect, so I would advise to not get your inspiration from it. 

To represent a hashtag using the subject property I would advise something like:

        "subject": [{
            "name" : "#iptcrocks",
            "rel" : "hashtag"
        }]

Using "drol:hashtag" for the rel property doesn't really fit ninjs as QCodes don't exist in ninjs. 

Best,
Philippe Mougin

**Comment by sdavids13** [comment]
Thanks @pmougin, is there any guidance that the ninjs community can provide commonly used `rel` values? Ideally these would be documented in the json schema using the `examples` keyword (though that was introduced in json schema v6 which is newer than the current v4).

**Comment by jolla56** [comment]
See 2.0 schema
