### ISSUE TITLE
rel vs role in infosource

### ISSUE THREAD

**Issue by bquinn** [iptc/newsinjson#74]
At today's meeting we noticed that infosource has "rel" but in NewsML-G2, infosource has "role".

In 2.0, we should fix this and use "role" in the same way as we do in G2.

### Role or roles?

To make it truly G2 compatible we should also support multiple roles... but we're not sure if it's really necessary and it would make the schema more complicated and harder to use. (We could also achieve this with multiple infosource instances for the same person with different roles)

DECISION: keep it simple, only one role value but it can be expressed with multiple infosource items.

** NOTE also check person, place etc (G2 subject) to see whether `role` is correct in the ninjs version.

**Comment by bquinn** [comment]
Follow-up to the note above, comparing with the equivalent properties in G2:

`<subject>` in NewsML-G2 doesn't have rel _or_ role attributes!

It has "how", "why", "rank", "relevance", "qcode", "rank"... but nothing that could really be seen as "rel" or "role".

There is "type", defined as "The type of the concept assigned as controlled property value, expressed by a QCode" (and an equivalent "typeuri").

Can we say that rel is equivalent to type in G2? I'm not sure...

**Comment by jolla56** [comment]
But for infosource it is not clear if the schema+code identify the name of the inforsource or the rel/role.
3:14
In NewsML-G2 the infoSource is of type Flex1PartyPropType.
3:14
It extends the FlexPartyPropType with a role and a roleuri.

**Comment by bquinn** [comment]
Discussion today:

Three questions:
1. should we change rel to role in ninjs?
2. should it be multi-valued?
3. should the value be a URI or a string?

1. subject in G2 doesn't have rel or role, but maybe it should! Currently declaring subject in G2 is equivalent of saying "this is the subject of the story", and mentions can be declared as an `<assert>` that is linked to the content with `<inlineRef>`. This is complex and could be simplified by adding role to subject in G2. Then we could add it to ninjs too, and keep compatibility.

2 is easy, decided above: no it should be single-valued.

3: we probably want it to be a string because we're keeping things simple in ninjs.

PROPOSAL:
We keep `rel` on person, organisation, place, subject, event, object. Infosource still needs to be decided, see @jolla56 's point above.

**Comment by nitmws** [comment]
My comments with a NewsML-G2 background:

* @rel and @role have quite different semantics: (note: sorry role appears in uppercase in Github markdown automatically)
  * @role is the refinement of the semantics of the metadata property XML element it is applied to. 
  Example: A _description_ is a free text description of the content in a generic way, These NewsCodes, to be used with @role, show specific kinds of a description: http://cv.iptc.org/newscodes/descriptionrole/ ... e.g. "caption" (for photos) or "teaser".
  Conclusion: a @role makes only sense as attribute of an XML element being a metadata property.
  * @rel adds the RDF Predicate to an XML element which is a/ a generic kind of metadata property which b/ has no specific semantics. Short wrap up: RDF triples can be retrieved from NewsML-G2 Items: the RDF Subject is set by itemMeta (the item as a whole), contentMeta (the content as a whole) or partMeta (a specific part of the content). The RDF Predicate is expressed by such a metadata property XML element: its tag and definition defines the Predicate ... and its value sets the RDF Object of the triple. 
  Therefore the @rel attribute is typical for all the xxxExtProperty elements having this as definition: "the semantics are defined by the concept referenced by the rel attribute." Another good example is the <related> element in a _concept_: it can be used to express a relations of "this" concept to another concept or literal value which is not covered by all the other child elements of _concept_
* Answer to question 1: no, please not as these two attributes have quite different semantics.
* Re question 2: actually yes as in NewsML-G2 e.g. the contentMeta wrapper may have multiple <contentMetaExtProperty> elements and an item may have many _description_ s with different @role attributes.
* Re question 3: I lean towards a URI as both the semantics expressed by @role and the relationship expressed by @rel need a deeper description than just a short literal value, in other words: the value should be a concept.
* re issue 4: It SHOULD NOT have a @rel as the <subject> property has already semantics. If it may have a @role was discussed already in 2005 or so. This went along lines like "it should be refined if subject means the value (= RDF object) is an important concept of the content, or only mentioned". To solve this the @relevance was added :-) I think there will always be different views if "this content" "has as important topic" "....", or "this content" "is about" "...."  is too generic or not. I think it's more the "is about" raising the question "in which way is the content about that concept".

Re the "re 3" above: it should be considered if ninjs should be relevant in an semantic technology context. In other words: should it be be possible to generate a JSON-LD object from a ninjs-object? If yes I recommend using URIs and not strings.
