### ISSUE TITLE
Inconsistent property names in 2.0 dev schema for headline vs body

### ISSUE THREAD

**Issue by bquinn** [iptc/newsinjson#77]
For body we have

                "properties": {
                    "name": {
                        "title": "Name",
                        "description": "The name identifying this body",
                        "type": "string"
                    },
                    "value": {
                        "title": "Value",
                        "description": "The body text identified with the above name.",
                        "type": "string"
                    }                    
                }

but for headline we have 

               "properties": {
                    "name": {
                        "title": "Name",
                        "description": "The name identifying this headline",
                        "type": "string"
                    },
                    "text": {
                        "title": "Value",
                        "description": "The headline identified with the above name.",
                        "type": "string"
                    }                    
                }

ie "value" vs "text". Shouldn't they be consistently named?

**Comment by jolla56** [comment]
Maybe not?
The headline is a textline as a string.

The body can be anything. It can contain markup etc. We might still decide on the same property name. But I think the content can be very different.

**Comment by bquinn** [comment]
Well, the description says "body text"... :-)

**Comment by jolla56** [comment]
So if we change that to body content? The main issue, I think, is if we feel like indicating there is a difference, or at least a potential difference in format. Or if it is better to use the same property name. But if so I would use value for headline too.

**Comment by nitmws** [comment]
My 5ct on that: ninjs 1.3 defines ^body_... as "The textual content of the news object." The text may be formatted differently (plain, HTML, XML). 
So what's the goal for "body" in ninjs 2.0: to stick to text content in different formats or to open it to any kind of content, including images, video, audio - but that's covered by the renditions property.
