### ISSUE TITLE
Add property contentcreated

### ISSUE THREAD

**Issue by nitmws** [iptc/newsinjson#78]
Working with ninjs I noticed that a property for the date when the content as such was created is missing.

IPTC NewsML-G2 has contentCreated and the IPTC Photo Metadata has a Date Created.

ninjs has versioncreated but this aligns with the NewsML-G2 versionCreated: its the timestamp of when this version of this news item was created. Photos may be taken and audio may be recorded significantly before a news item (version) is created and this needs to be reflected.

**Comment by jolla56** [comment]
Good idea.
