### ISSUE TITLE
altid missing from 2.0 dev schema

### ISSUE THREAD

**Issue by bquinn** [iptc/newsinjson#80]
I noticed while creating test cases that "altid" doesn't exist in the new schema.

The 1.3 schema says:

        "altids": {
            "title": "Alternative id",
            "description": "Alternative identifiers of the item. It is up to the individual provider to name and set type on the alternative identifiers they like to use. nar:altId issue #3. (Added in version 1.3)",
            "type": "object",
            "additionalProperties": true
        },

So we need to think about how to handle this but in a way that works with protobufs.

**Comment by jolla56** [comment]
If we like to leave altid open like this it might be an example of an extension in protobuf:

Extensions
Extensions let you declare that a range of field numbers in a message are available for third-party extensions. An extension is a placeholder for a field whose type is not defined by the original .proto file. This allows other .proto files to add to your message definition by defining the types of some or all of the fields with those field numbers. Let's look at an example:


message Foo {
  // ...
  extensions 100 to 199;
}
This says that the range of field numbers [100, 199] in Foo is reserved for extensions. Other users can now add new fields to Foo in their own .proto files that import your .proto

**Comment by bquinn** [comment]
It's just worth adding for the record that we resolved this question by deciding that `altids` in 2.0 should be an array of name/value pairs.
