### ISSUE TITLE
expiry / expiration dates for ninjs content

### ISSUE THREAD

**Issue by bquinn** [iptc/newsinjson#90]
[On the groups.io list back in August 2020, Johan wrote:](https://groups.io/g/iptc-news-in-json-dev/topic/76383583#979)

> We are planning to start using advice but for lifetime we have a usecase of setting a specific date and time as end of lifetime.
> 
> Not allowed here:
> 

> ```
>    "lifetime": {
>      "type": "object",
>      "description": "Advice regarding the length of time that the content is considered to be relevant. Experimental vocabulary, part of the C-POP project.",
>      "additionalProperties": false,
>      "properties": {
>        "code": {
>          "type": "string",
>          "description": "Present values are: short, medium, long and evergreen."
>        },
>        "scheme": {
>          "type": "string",
>          "format": "uri",
>          "description": "http://cv.iptc.org/newscodes/advice-lifetime"
>        }
>      }
>    }
> ```
> 

Paul replied:

> Is that likely to be a different end-of-life for different usages of the content?
> 
> Just wondering if the G2 itemMeta 'expires' property is a better fit.

Heather (@hledwards) revived the idea in July 2021:

> Hello all,
> 
> @pauliharman and all, was there ever a conclusion on a ninjs implementation for expiration dates?  I've been digging around in both groups plus git and have found questions (most recently this one) but no decisions.  
> 
> We are already using nar:expires in our G2 implementation but don't have a solution for our json implementation.

Johan wrote:

> Maybe something to consider for our 2.0. But in advice or as a separate property?

**Comment by bquinn** [comment]
I think my vote would be to have a separate property called `expires` or `expirydate` etc. "lifetime" sounds a bit less concrete and as Paul suggests, as we can have multiple `advice` blocks, we could have multiple `lifetime` dates/values for different audiences.

Another way to say it is that the lifetime concerns how long the content is relevant *for a certain audience*, but `expires` is a property of the content itself.

Examples (I'm making these up here):

* A news item which is a preview of a football match should `expire` the moment the game starts (or not? how are these usually handled?)
* A video of a football goal which has been licensed for two days of use needs to `expire` on the exact day and time that the licence expires.
* A mid-day stockmarket update should have a `lifetime` of half a day, because it's not really relevant any more, but it doesn't *have* to be removed.
* An article about pumpkin pie recipes has a `lifetime` until Thanksgiving, but it doesn't *have* to be removed. And it may be revived next year.

But it's a subtle difference. Can we find some better examples that make it easier to decide whether there is a real difference?

**Comment by jolla56** [comment]
I think your second exmple is more a rights things since it is mandatory. The other are suggestions where publication is ok if the publisher so choses.

**Comment by jolla56** [comment]
Meeting Nov 15: Create a property called expires as a date-time. 
How does that work with advice/lifetime?  New property under lifetime?
If a separate property how to explain the relationship?

**Comment by jolla56** [comment]
Added to both dev schemas.
