### ISSUE TITLE
"genre" should be "genres" to match new pluralisation rules

### ISSUE THREAD

**Issue by bquinn** [iptc/newsinjson#91]
We noticed today that one property is still singular: "genre".

https://github.com/iptc/newsinjson/blob/75ff067d262408fa966a6de80c1f3227e3a2845f/specification/ninjs-schema_dev_2.0.json#L652

This should be fixed.

**Comment by jolla56** [comment]
Can something belong to several genres?
Is genre in NAR singular or plural?

**Comment by bquinn** [comment]
> Can something belong to several genres?
I think so... looking at https://cv.iptc.org/newscodes/genre we have "Exclusive", "Sponsored", "

> Is genre in NAR singular or plural?
The name of the element is "genre", but then we also have "subject" etc in singular because in XML you can simply repeat a field, whereas in JSON you need to wrap multiple fields in a container object of some sort. Also, `genre` in NewsML-G2 is repeatable - see https://www.iptc.org/std/NewsML-G2/2.29/specification/NewsML-G2-2.29-specification.html#_descriptive_metadata.

**Comment by jolla56** [comment]
Done.
