### ISSUE TITLE
Suggestion: Add simple "headline" and "body" properties and call the arrays "altheadlines" and "altbodies"

### ISSUE THREAD

**Issue by bquinn** [iptc/newsinjson#92]
Looking at the examples, they seem more complicated than we would like, so could we go back to having a separate "headline" property? To be discussed when Johan is back!

**Comment by jolla56** [comment]
I'm ok with that, but will that lead to a simple description and a simple body too?

**Comment by jolla56** [comment]
At the meeting Aug 23 we decided - NO
