### ISSUE TITLE
Q: Should "bodies" elements always be different technical formats of the same editorial body a la NewsML-G2?

### ISSUE THREAD

**Issue by bquinn** [iptc/newsinjson#96]
e.g. should we be able to have `"role": "long"` and `"role": "short"`?

Or should we be strict and allow only technical formats?

An example could be a body in plain text, XHTML, AMP format, Apple News format, and Facebook Instant Articles format. These would be defined as roles. (Several of them would probably have the same contenttype, so we couldn't use the contenttype property alone as a way to distinguish these bodies from each other.)

This is probably more a documentation question than a schema one, the schema may not need to change but we should be clear about how we intend it to be used.

**Comment by jolla56** [comment]
We can extend the documentation, but I don't think we should be too restrictive. If providers have use for roles we have not thought of it is better to be open and flexible. And what is the definition of technical format and other stuff?

**Comment by jolla56** [comment]
Done.
